name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy with pm2
        env:
          DO_SSH_PRIVATE_KEY: ${{ secrets.DO_SSH_PRIVATE_KEY }}
        run: |
          echo "${DO_SSH_PRIVATE_KEY}" > deploy_key
          chmod 600 deploy_key
          ssh -o "StrictHostKeyChecking=no" -i deploy_key jay@139.59.40.42 "cd /home/jay/app && git pull && yarn && pm2 reload pm2.config.json"
